In [1]:
import numpy as np

In [2]:
x = [1,2,3.5,4.8]

In [3]:
type(x)

list

In [4]:
2*x

[1, 2, 3.5, 4.8, 1, 2, 3.5, 4.8]

In [6]:
x

[1, 2, 3.5, 4.8]

In [12]:
a = np.array(x,dtype=np.float32)
print(a)

[1.  2.  3.5 4.8]


In [13]:
type(a)

numpy.ndarray

In [14]:
print(a*2)

[2.  4.  7.  9.6]


In [15]:
a.dtype

dtype('float32')

In [16]:
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [19]:
print(x[0])
print(x[-1])
print(x[0:3:2])

1
9
[1 5]


In [20]:
x = np.arange(3.2)
y = np.arange(0.1,1.2,0.1)
print(x)
print(y)


[0. 1. 2. 3.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1]


In [21]:
v1 = np.arange(5)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,5)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-10,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)

Creating a numpy array via arange (stop=5) : [0 1 2 3 4]

Creating a numpy array via arange (start=2,stop=5) : [2 3 4]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6 -8]



In [22]:
[[1,1],[2,2], [3,3]]

[[1, 1], [2, 2], [3, 3]]

In [24]:
b = np.array([[1,1],[2,2], [3,3]])

print(b.ndim,b.size)
print(b)

2 6
[[1 1]
 [2 2]
 [3 3]]


In [25]:
b.shape

(3, 2)

In [23]:
np.shape(b)

(3, 2)

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a.shape

(3, 4)

In [28]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
a.reshape(2,3,-1).shape

(2, 3, 2)

In [32]:
a.reshape(-1).shape

(12,)

In [33]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [34]:
a = np.linspace(0, 4, 9)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [39]:
x = np.zeros((2, 3,10,7,4))
x;

In [40]:
x.shape

(2, 3, 10, 7, 4)

In [30]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.diag([1,2,3,4,-1])

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, -1]])

In [43]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [44]:
x = np.array([1, 2, 3])
np.repeat(x, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [45]:
x = np.diag([1,2,3,4,-1])
x

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0,  4,  0],
       [ 0,  0,  0,  0, -1]])

In [49]:
x[1:4,1:4]

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [52]:
np.sin(x).astype(np.float16)

array([[ 0.8413,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.909 ,  0.    ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.1411,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , -0.757 ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    , -0.8413]], dtype=float16)

In [55]:
mat = np.random.normal(2,2.5,(40,80))
mat.shape

(40, 80)

In [56]:
print ('Overall mean of matrix is \n%s\n'%np.mean(mat))

Overall mean of matrix is 
2.0514996880459915



In [59]:
print ('Row mean of matrix is \n%s\n'%np.mean(mat, axis=0).shape)

Row mean of matrix is 
80



In [75]:
print ('Column mean of matrix is \n%s\n'%np.mean(mat, axis=1))

Column mean of matrix is 
[1.24481911 1.77027403 2.90012805 1.96667605]



In [60]:
print ('Overall varience of matrix is %s\n'%np.var(mat))

Overall varience of matrix is 6.137525143453068



In [61]:
print ('Overall standard deviation of matrix is %s\n'%np.std(mat))

Overall standard deviation of matrix is 2.4774029029314284



In [62]:
print ('Overall sum of matrix is %s\n'%np.sum(mat))

Overall sum of matrix is 6564.799001747173



In [63]:
print ('Overall min of matrix is %s\n'%np.min(mat))

Overall min of matrix is -6.040891599076552



In [64]:
print ('Overall max of matrix is %s\n'%np.max(mat))

Overall max of matrix is 10.914840206511437



In [65]:
marks = np.array([30,31,32,40,90,95,97,98,99,100])
print ('Marks = %s\n'%marks)
print ('Overall 30 percent quantile of marks is %s\n'%(str(np.percentile(marks,30))))

Marks = [ 30  31  32  40  90  95  97  98  99 100]

Overall 30 percent quantile of marks is 37.599999999999994



In [68]:
np.sum(np.zeros((10,15,20)),axis=(1,2)).shape

(10,)

In [70]:
# dir(np)

In [71]:
len(dir(np))

624

In [76]:
x = np.arange(10)+3
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
x>5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [78]:
x[x>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [79]:
np.where(x>5)

(array([3, 4, 5, 6, 7, 8, 9]),)

In [85]:
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [84]:
x[np.array([0,8])]

array([ 3, 11])

# Combining Data

In [86]:
data1 = np.random.randint(5,15,size=(5,3))

In [87]:
data2 = np.random.randint(5,15,size=(5,3))

In [88]:
np.hstack([data1,data2]).shape

(5, 6)

In [89]:
np.vstack([data1, data2]).shape

(10, 3)

In [94]:
np.concatenate([data1, data2], axis=1).shape

(5, 6)

In [95]:
np.stack([data1, data2], axis=2).shape

(5, 3, 2)

# Save and load data

In [96]:
x = np.linspace(0,5,100)
y = np.sin(x)

In [97]:
y.shape

(100,)

In [98]:
np.savetxt('x.txt',x)

In [99]:
np.savetxt('data.txt',np.c_[x,y])

In [101]:
x = np.loadtxt('data.txt')
x.shape

(100, 2)

In [109]:
# !cat x.txt

In [102]:
x = np.random.normal(0,1,(1000,1000))

In [103]:
np.savetxt('x.txt',x,)

In [104]:
np.save('xdata',x)

In [105]:
x = np.load('xdata.npy')

In [106]:
x.shape

(1000, 1000)

In [107]:
x = np.random.normal(0,1,(100,100))
y = np.random.normal(0,1,(100,100))
z = np.random.normal(0,1,(100,100))

In [109]:
np.savez('dataset',d1=x,d2=y,d3=z)

In [110]:
data = np.load('dataset.npz')

In [111]:
data.files

['d1', 'd2', 'd3']

In [112]:
x = data['d1']
y = data['d2']
z = data['d3']

In [114]:
x = np.diag([1,2])
y = np.ones((2,2))

In [115]:
x

array([[1, 0],
       [0, 2]])

In [116]:
y

array([[1., 1.],
       [1., 1.]])

In [117]:
x*y

array([[1., 0.],
       [0., 2.]])

In [118]:
np.dot(x,y)

array([[1., 1.],
       [2., 2.]])

In [126]:
x = np.random.normal(0,1,[5,5])
np.linalg.inv(x)
np.linalg.eigvals(x).astype(np.complex64)

array([ 0.15090637+2.446889j ,  0.15090637-2.446889j ,
       -0.53086835+0.j       ,  1.4531221 +0.9358685j,
        1.4531221 -0.9358685j], dtype=complex64)

In [ ]:
x = np.array([1,1,2])
pdf, ebin = np.histogram(x,2)
cbin = 0.5*(ebin[1:]+ebin[:-1])

pdf,cbin